dubbo:
  application:
    name: account
    # 关闭序列化校验，否则生成的class将不会通过校验
    serialize-check-status: DISABLE
  protocol:
    name: dubbo
    port: -1
    accesslog: true
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181